const fs = require('fs');
const lines = fs.readFileSync('src/components/finance/MonthlyPayrollRuns.tsx', 'utf8').split('\n');

const startIdx = lines.findIndex(l => l.includes('return filtered.map((emp) => {'));
const endIdx = lines.findIndex(l => l.includes('}); })()}'));

if (startIdx !== -1 && endIdx !== -1 && startIdx < endIdx) {
  // Let's create the replacement array manually in JS
  let newLines = [];
  newLines.push('                          return filtered.map((emp) => {');
  newLines.push('                            const canModifyRow = selectedRun.status === "Draft" || selectedRun.status === "Needs Modification" || selectedRun.status === "Under Modification";');
  newLines.push('                            const netRemaining = Math.max(0, emp.netSalary - (emp.muddahAmount || 0));');
  newLines.push('                            return (');
  newLines.push('                              <tr key={emp.id} className="border-b border-slate-100/50 hover:bg-slate-50/50 transition-colors">');
  newLines.push('                                {/* EMPLOYEE INFO */}');
  newLines.push('                                <td className="py-4 px-4 sticky right-0 bg-white z-10 border-l border-slate-200">');
  newLines.push('                                  <div className="font-bold text-slate-800 text-[13.5px] font-arabic flex items-center gap-2">');
  newLines.push('                                    {emp.arabicName}');
  newLines.push('                                    {emp.company && (');
  newLines.push('                                      <span className={`text-[9px] px-1.5 py-0.5 rounded border ${');
  newLines.push('                                        emp.company.includes("ساين")');
  newLines.push('                                          ? "bg-purple-50 text-purple-700 border-purple-100"');
  newLines.push('                                          : "bg-blue-50 text-blue-700 border-blue-100"');
  newLines.push('                                      }`}>');
  newLines.push('                                        {emp.company}');
  newLines.push('                                      </span>');
  newLines.push('                                    )}');
  newLines.push('                                  </div>');
  newLines.push('                                  <div className="text-[10.5px] text-slate-500 font-mono font-bold mt-0.5">');
  newLines.push('                                    ID: {emp.employeeId} | {emp.jobTitle}');
  newLines.push('                                  </div>');
  newLines.push('                                </td>');
  newLines.push('');
  newLines.push('                                {/* BANK INFO */}');
  newLines.push('                                <td className="py-4 px-4 bg-sky-50/20">');
  newLines.push('                                  <div className="space-y-1 text-right max-w-[140px]">');
  newLines.push('                                    <div className="flex items-center gap-1">');
  newLines.push('                                      <span className="text-[9px] text-slate-400">البنك:</span>');
  newLines.push('                                      <InlineEditable type="text" value={emp.bankName || ""} onSave={(val) => handleInlineSave(emp.id, "bankName", val)} disabled={!canModifyRow || !isAccountant} className="font-arabic font-bold text-[10px] w-[80px] text-right" />');
  newLines.push('                                    </div>');
  newLines.push('                                    <div className="flex items-center gap-1">');
  newLines.push('                                      <span className="text-[9px] text-slate-400">IBAN:</span>');
  newLines.push('                                      <InlineEditable type="text" value={emp.iban || ""} onSave={(val) => handleInlineSave(emp.id, "iban", val)} disabled={!canModifyRow || !isAccountant} className="font-mono font-bold text-[10px] tracking-tight text-right w-[110px]" />');
  newLines.push('                                    </div>');
  newLines.push('                                  </div>');
  newLines.push('                                </td>');
  newLines.push('');
  newLines.push('                                {/* EARNINGS */}');
  newLines.push('                                <td className="py-4 px-3 font-mono font-bold text-slate-700 text-center"><InlineEditable value={emp.basicSalary} onSave={(val) => handleInlineSave(emp.id, "basicSalary", val)} disabled={!canModifyRow || !isAccountant} /></td>');
  newLines.push('                                <td className="py-4 px-3 font-mono font-bold text-slate-700 text-center"><InlineEditable value={emp.housingAllowance} onSave={(val) => handleInlineSave(emp.id, "housingAllowance", val)} disabled={!canModifyRow || !isAccountant} /></td>');
  newLines.push('                                <td className="py-4 px-3 font-mono font-bold text-slate-700 text-center"><InlineEditable value={emp.transportAllowance} onSave={(val) => handleInlineSave(emp.id, "transportAllowance", val)} disabled={!canModifyRow || !isAccountant} /></td>');
  newLines.push('                                <td className="py-4 px-3 font-mono font-bold text-slate-700 text-center"><InlineEditable value={emp.foodAllowance} onSave={(val) => handleInlineSave(emp.id, "foodAllowance", val)} disabled={!canModifyRow || !isAccountant} /></td>');
  newLines.push('                                <td className="py-4 px-3 font-mono font-bold text-indigo-600 text-center" style={{ display: "none" }}><InlineEditable value={emp.muddahAmount} onSave={(val) => handleInlineSave(emp.id, "muddahAmount", val)} disabled={!canModifyRow || !isAccountant} /></td>');
  newLines.push('                                <td className="py-4 px-3 font-mono font-bold text-indigo-600 text-center"><InlineEditable value={emp.overtimeHours} onSave={(val) => handleInlineSave(emp.id, "overtimeHours", val)} disabled={!canModifyRow || !isAccountant} /></td>');
  newLines.push('                                <td className="py-4 px-3 font-mono font-bold text-indigo-600 text-center"><InlineEditable value={emp.overtimeAmount} onSave={(val) => handleInlineSave(emp.id, "overtimeAmount", val)} disabled={!canModifyRow || !isAccountant} /></td>');
  newLines.push('                                <td className="py-4 px-3 font-mono font-bold text-[#0072BC] text-center"><InlineEditable value={emp.otherAllowances} onSave={(val) => handleInlineSave(emp.id, "otherAllowances", val)} disabled={!canModifyRow || !isAccountant} /></td>');
  newLines.push('');
  newLines.push('                                {/* DEDUCTIONS */}');
  newLines.push('                                {showDetailedDeductions && (');
  newLines.push('                                  <>');
  newLines.push('                                    <td className="py-4 px-3 font-mono font-bold text-rose-600 text-center"><InlineEditable value={emp.loansDeduction} onSave={(val) => handleInlineSave(emp.id, "loansDeduction", val)} disabled={!canModifyRow || !isAccountant} /></td>');
  newLines.push('                                    <td className="py-4 px-3 font-mono font-bold text-rose-600 text-center"><InlineEditable value={emp.absenceDeduction} onSave={(val) => handleInlineSave(emp.id, "absenceDeduction", val)} disabled={!canModifyRow || !isAccountant} /></td>');
  newLines.push('                                    <td className="py-4 px-3 font-mono font-bold text-rose-600 text-center"><InlineEditable value={emp.lateDeduction} onSave={(val) => handleInlineSave(emp.id, "lateDeduction", val)} disabled={!canModifyRow || !isAccountant} /></td>');
  newLines.push('                                    <td className="py-4 px-3 font-mono font-bold text-rose-600 text-center"><InlineEditable value={emp.penaltyDeduction} onSave={(val) => handleInlineSave(emp.id, "penaltyDeduction", val)} disabled={!canModifyRow || !isAccountant} /></td>');
  newLines.push('                                    <td className="py-4 px-3 font-mono font-bold text-rose-600 text-center"><InlineEditable value={emp.gosiDeduction} onSave={(val) => handleInlineSave(emp.id, "gosiDeduction", val)} disabled={!canModifyRow || !isAccountant} /></td>');
  newLines.push('                                  </>');
  newLines.push('                                )}');
  newLines.push('                                ');
  newLines.push('                                {/* OTHER DEDUCTIONS */}');
  newLines.push('                                <td className="py-4 px-3 font-mono font-bold text-rose-600 text-center">');
  newLines.push('                                  <InlineEditable value={emp.otherDeductions} onSave={(val) => handleInlineSave(emp.id, "otherDeductions", val)} disabled={!canModifyRow || !isAccountant} />');
  newLines.push('                                </td>');
  newLines.push('');
  newLines.push('                                {/* SUMMARY */}');
  newLines.push('                                <td className="py-4 px-3 font-mono font-bold text-indigo-600 text-center">');
  newLines.push('                                  {emp.netSalary.toLocaleString("en-US")}');
  newLines.push('                                </td>');
  newLines.push('                                <td className="py-4 px-3 font-mono font-bold text-amber-600 text-center bg-amber-50/30">');
  newLines.push('                                  <InlineEditable value={emp.muddahAmount || 0} onSave={(val) => handleInlineSave(emp.id, "muddahAmount", val)} disabled={!canModifyRow || !isAccountant} />');
  newLines.push('                                </td>');
  newLines.push('                                <td className="py-4 px-3 font-mono font-bold text-emerald-600 text-center bg-emerald-50/20">');
  newLines.push('                                  {netRemaining.toLocaleString("en-US")}');
  newLines.push('                                </td>');
  newLines.push('');
  newLines.push('                                {/* TRANSFER STATUS */}');
  newLines.push('                                <td className="py-4 px-3 text-center">');
  newLines.push('                                  <span className={`text-[9px] px-2 py-0.5 rounded-full font-bold ${emp.transferStatus === "Transferred" ? "bg-emerald-100 text-emerald-700" : "bg-slate-100 text-slate-500"}`}>');
  newLines.push('                                    {emp.transferStatus === "Transferred" ? "تم التحويل" : "بانتظار التحويل"}');
  newLines.push('                                  </span>');
  newLines.push('                                </td>');
  newLines.push('');
  newLines.push('                                {/* ACTIONS */}');
  newLines.push('                                <td className="py-4 px-4 text-left">');
  newLines.push('                                  <div className="flex items-center justify-end gap-1">');
  newLines.push('                                    <button');
  newLines.push('                                      onClick={() => {');
  newLines.push('                                        setSelectedPayslipEmployee(emp);');
  newLines.push('                                        setIsPayslipModalOpen(true);');
  newLines.push('                                      }}');
  newLines.push('                                      className="px-2 py-1 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded text-[10px] font-bold flex items-center gap-0.5"');
  newLines.push('                                      title="عرض كشف الراتب الفردي"');
  newLines.push('                                    >');
  newLines.push('                                      <FileText className="w-3 h-3" />');
  newLines.push('                                      كشف راتب');
  newLines.push('                                    </button>');
  newLines.push('                                    {canModifyRow && (');
  newLines.push('                                      <button');
  newLines.push('                                        onClick={() => {');
  newLines.push('                                          handleRemoveEmployeeRow(emp.id);');
  newLines.push('                                        }}');
  newLines.push('                                        className="px-2 py-1 bg-rose-50 hover:bg-rose-100 text-rose-600 rounded text-[10px] font-bold flex items-center gap-0.5"');
  newLines.push('                                        title="حذف الموظف من المسير"');
  newLines.push('                                      >');
  newLines.push('                                        <Trash2 className="w-3 h-3" />');
  newLines.push('                                        حذف');
  newLines.push('                                      </button>');
  newLines.push('                                    )}');
  newLines.push('                                  </div>');
  newLines.push('                                </td>');
  newLines.push('                              </tr>');
  newLines.push('                            );');
  newLines.push('                          }); })()}');

  lines.splice(startIdx, endIdx - startIdx + 1, ...newLines);
  fs.writeFileSync('src/components/finance/MonthlyPayrollRuns.tsx', lines.join('\n'));
  console.log("Success replacing array.");
} else {
  console.log("Failed to find bounds.");
}
