sed -i 's/<td className="py-4 px-3 font-mono font-bold text-rose-600 text-center"><InlineEditable mod={emp.modifications?.find(m => m.field === "loansDeduction")} value={emp.loansDeduction} onSave={(val) => handleInlineSave(emp.id, "loansDeduction", val)} disabled={!canModifyRow || !isAccountant} \/><\/td>/<td className="py-4 px-3 font-mono font-bold text-rose-600 text-center"><ClickableDeduction mod={emp.modifications?.find(m => m.field === "loansDeduction")} value={emp.loansDeduction} onClick={() => handleOpenDeductionsModal(emp)} disabled={false} \/><\/td>/g' src/components/finance/MonthlyPayrollRuns.tsx

sed -i 's/<td className="py-4 px-3 font-mono font-bold text-rose-600 text-center"><InlineEditable mod={emp.modifications?.find(m => m.field === "absenceDeduction")} value={emp.absenceDeduction} onSave={(val) => handleInlineSave(emp.id, "absenceDeduction", val)} disabled={!canModifyRow || !isAccountant} \/><\/td>/<td className="py-4 px-3 font-mono font-bold text-rose-600 text-center"><ClickableDeduction mod={emp.modifications?.find(m => m.field === "absenceDeduction")} value={emp.absenceDeduction} onClick={() => handleOpenDeductionsModal(emp)} disabled={false} \/><\/td>/g' src/components/finance/MonthlyPayrollRuns.tsx

sed -i 's/<td className="py-4 px-3 font-mono font-bold text-rose-600 text-center"><InlineEditable mod={emp.modifications?.find(m => m.field === "lateDeduction")} value={emp.lateDeduction} onSave={(val) => handleInlineSave(emp.id, "lateDeduction", val)} disabled={!canModifyRow || !isAccountant} \/><\/td>/<td className="py-4 px-3 font-mono font-bold text-rose-600 text-center"><ClickableDeduction mod={emp.modifications?.find(m => m.field === "lateDeduction")} value={emp.lateDeduction} onClick={() => handleOpenDeductionsModal(emp)} disabled={false} \/><\/td>/g' src/components/finance/MonthlyPayrollRuns.tsx

sed -i 's/<td className="py-4 px-3 font-mono font-bold text-rose-600 text-center"><InlineEditable mod={emp.modifications?.find(m => m.field === "penaltyDeduction")} value={emp.penaltyDeduction} onSave={(val) => handleInlineSave(emp.id, "penaltyDeduction", val)} disabled={!canModifyRow || !isAccountant} \/><\/td>/<td className="py-4 px-3 font-mono font-bold text-rose-600 text-center"><ClickableDeduction mod={emp.modifications?.find(m => m.field === "penaltyDeduction")} value={emp.penaltyDeduction} onClick={() => handleOpenDeductionsModal(emp)} disabled={false} \/><\/td>/g' src/components/finance/MonthlyPayrollRuns.tsx

sed -i 's/<td className="py-4 px-3 font-mono font-bold text-rose-600 text-center"><InlineEditable mod={emp.modifications?.find(m => m.field === "gosiDeduction")} value={emp.gosiDeduction} onSave={(val) => handleInlineSave(emp.id, "gosiDeduction", val)} disabled={!canModifyRow || !isAccountant} \/><\/td>/<td className="py-4 px-3 font-mono font-bold text-rose-600 text-center"><ClickableDeduction mod={emp.modifications?.find(m => m.field === "gosiDeduction")} value={emp.gosiDeduction} onClick={() => handleOpenDeductionsModal(emp)} disabled={false} \/><\/td>/g' src/components/finance/MonthlyPayrollRuns.tsx

sed -i 's/<InlineEditable mod={emp.modifications?.find(m => m.field === "otherDeductions")} value={emp.otherDeductions} onSave={(val) => handleInlineSave(emp.id, "otherDeductions", val)} disabled={!canModifyRow || !isAccountant} \/>/<ClickableDeduction mod={emp.modifications?.find(m => m.field === "otherDeductions")} value={emp.otherDeductions} onClick={() => handleOpenDeductionsModal(emp)} disabled={false} \/>/g' src/components/finance/MonthlyPayrollRuns.tsx

