const fs = require('fs');
let code = fs.readFileSync('src/components/hr/InstantDocumentsHub.tsx', 'utf8');

const replacement = `
  const getTemplateText = () => {
    if (!selectedDocEmp) return '';
    const d = new Date().toISOString().slice(0, 10);
    const totalSalary = (selectedDocEmp.basicSalary || 0) + (selectedDocEmp.allowances?.housing || 0) + (selectedDocEmp.allowances?.transport || 0);

    if (letterLang === 'en') {
      switch(docTemplate) {
        case 'salary_cert': return \`Ref: HR-SAL-\${selectedDocEmp.id}-26\\nDate: \${d}\\n\\nSubject: Salary Certificate & Employment Proof\\n\\nTo Whom It May Concern,\\n\\nThis is to certify that \${selectedDocEmp['arabicName']} (ID: \${selectedDocEmp.iqamaId}) is an employee of our company, working as \${selectedDocEmp.jobTitle} in the \${selectedDocEmp.department || 'Operations'} department since \${selectedDocEmp.dateOfJoining}.\\n\\nFinancial Details:\\n- Basic Salary: SAR \${selectedDocEmp.basicSalary || 0}\\n- Allowances: SAR \${(selectedDocEmp.allowances?.housing || 0) + (selectedDocEmp.allowances?.transport || 0)}\\n- Total Monthly Salary: SAR \${totalSalary}\\n\\nThis certificate is issued upon the employee's request without any liability to the company.\\n\\nHR Department\\nCompany Administration\`;
        case 'warning': return \`Ref: HR-WRN-\${selectedDocEmp.id}-26\\nDate: \${d}\\n\\nSubject: Official Warning Letter\\n\\nDear \${selectedDocEmp['arabicName']}, working as \${selectedDocEmp.jobTitle},\\n\\nThis letter serves as an official warning regarding your recent conduct/performance. You are expected to adhere strictly to the company's policies and procedures.\\n\\nFurther violations may result in disciplinary actions up to termination.\\n\\nHR Department\`;
        case 'termination': return \`Ref: HR-TERM-\${selectedDocEmp.id}-26\\nDate: \${d}\\n\\nSubject: Notice of Contract Termination\\n\\nDear \${selectedDocEmp['arabicName']}, working as \${selectedDocEmp.jobTitle},\\n\\nWe regret to inform you that your employment with the company is terminated effectively. Please coordinate with HR and Finance for your final settlement.\\n\\nHR Department\`;
        case 'employee_intro': return \`Ref: INTRO-FAW-\${selectedDocEmp.id}-26\\nDate: \${d}\\n\\nSubject: Employee Introduction Letter\\n\\nTo Whom It May Concern,\\n\\nWe certify that \${selectedDocEmp['arabicName']} (ID/Iqama: \${selectedDocEmp.iqamaId}) is a confirmed employee in our company under the title \${selectedDocEmp.jobTitle}.\\n\\nHR Department\`;
        case 'work_start': return \`Ref: START-FAW-\${selectedDocEmp.id}-26\\nDate: \${d}\\n\\nSubject: Commencement of Duty\\n\\nThis is to confirm that \${selectedDocEmp['arabicName']} (ID: \${selectedDocEmp.iqamaId}), appointed as \${selectedDocEmp.jobTitle}, has officially started/resumed duty on \${d}.\\n\\nHR Department\`;
        case 'probation_fix': return \`Ref: CONFIRM-FAW-\${selectedDocEmp.id}-26\\nDate: \${d}\\n\\nSubject: Employment Confirmation\\n\\nDear \${selectedDocEmp['arabicName']}, \${selectedDocEmp.jobTitle},\\n\\nWe are pleased to inform you that you have successfully completed your probation period. You are now a confirmed employee.\\n\\nHR Department\`;
        case 'transfer': return \`Ref: TRANS-FAW-\${selectedDocEmp.id}-26\\nDate: \${d}\\n\\nSubject: Employee Transfer Notice\\n\\nDear \${selectedDocEmp['arabicName']}, \${selectedDocEmp.jobTitle},\\n\\nBe informed that management has decided to transfer you to a new department/location effective immediately.\\n\\nHR Department\`;
        case 'promotion': return \`Ref: PROM-FAW-\${selectedDocEmp.id}-26\\nDate: \${d}\\n\\nSubject: Official Promotion Notice\\n\\nDear \${selectedDocEmp['arabicName']}, \\n\\nCongratulations! Based on your performance, you have been promoted. Your new role is [.....................] in the \${selectedDocEmp.department || 'Operations'} department.\\n\\nHR Department\`;
        case 'leave_request': return \`Ref: LEAVE-FAW-\${selectedDocEmp.id}-26\\nDate: \${d}\\n\\nSubject: Leave Application\\n\\nEmployee Name: \${selectedDocEmp['arabicName']}\\nJob Title: \${selectedDocEmp.jobTitle}\\n\\nI am applying for a leave starting from [......] to [......] for the following reason:\\n[.........................]\\n\\nEmployee Signature: ......................\\n\\nManager Approval: ......................\\nHR Approval: ......................\`;
        case 'contract': return \`Ref: CONT-FAW-\${selectedDocEmp.id}-26\\nDate: \${d}\\n\\nSubject: Employment Contract Draft\\n\\nFirst Party: Company Administration\\nSecond Party: \${selectedDocEmp['arabicName']} (ID: \${selectedDocEmp.iqamaId}), Title: \${selectedDocEmp.jobTitle}\\n\\nTotal Monthly Salary: SAR \${totalSalary}\\n\\nFirst Party Signature: ......................\\nSecond Party Signature: ......................\`;
        case 'custody_receipt': return \`Ref: CUST-FAW-\${selectedDocEmp.id}-26\\nDate: \${d}\\n\\nSubject: Custody / Asset Handover Receipt\\n\\nI, \${selectedDocEmp['arabicName']} (ID: \${selectedDocEmp.id}), \${selectedDocEmp.jobTitle}, acknowledge the receipt of the following company assets:\\n1. ..............................................................\\n2. ..............................................................\\n\\nEmployee Signature: ......................\\nStorekeeper Signature: ......................\`;
        default: return \`Subject: \${templatesList[docCategory]?.find((t) => t.id === docTemplate)?.name || 'Custom Document'}\\nRef: DOC-FAW-\${selectedDocEmp.id}-26\\nDate: \${d}\\n\\nEmployee Details:\\n- Name: \${selectedDocEmp['arabicName']}\\n- ID: \${selectedDocEmp.id} / \${selectedDocEmp.iqamaId}\\n- Title: \${selectedDocEmp.jobTitle}\\n- Department: \${selectedDocEmp.department || 'Operations'}\\n\\n------------------------------------------------\\n[Enter Document Details Here]\\n\\n\\n\\n\\n------------------------------------------------\\n\\nEmployee Signature: ......................................\\nManager Signature: ......................................\\nHR Signature: ......................................\`;
      }
    } else {
      switch(docTemplate) {
        case 'salary_cert': return \`الرقم المرجعي والتوثيق الآلي: HR-SAL-\${selectedDocEmp.id}-26\\nتاريخ صدور الخطاب الموثق: \${d}\\n\\nالموضوع: شهادة تفصيل الراتب والإفادة بمستحقات مالية\\n\\nإلى من يهمه الأمر المحترمين،\\nالسلام عليكم ورحمة الله وبركاته، أما بعد:\\n\\nتُفيد إدارة الشؤون الإدارية والموارد البشرية في "شركة فنون الوليد للصناعة" وبناءً على سجلاتها المعتمدة، بأن الموظف المذكورة بياناته أدناه، يعمل لدينا ولا يزال قائماً على رأس عمله ومباشراً لمهامه بانتظام وفق عقود العمل السارية.\\n\\nالبيانات التعريفية للموظف:\\n• الاسم الرباعي الموثق: \${selectedDocEmp['arabicName']}\\n• رقم الإثبات (هوية وطنية / إقامة): \${selectedDocEmp.iqamaId}\\n• الرقم الوظيفي لدى الشركة: \${selectedDocEmp.id}\\n• المسمى الوظيفي المعتمد: \${selectedDocEmp.jobTitle}\\n• مكان العمل والإدارة: \${selectedDocEmp.department || 'إدارة العمليات المركزية'}\\n• تاريخ بداية الخدمة والانضمام: \${selectedDocEmp.dateOfJoining}\\n\\nتفصيل البدلات والمستحقات المالية الشهرية (حسب المسير الأخير):\\n------------------------------------------------------------\\n1. الراتب الأساسي والمقطوع: \${selectedDocEmp.basicSalary || 0} ريال سعودي.\\n2. بدل السكن الشهري المُعتمد: \${selectedDocEmp.allowances?.housing || 0} ريال سعودي.\\n3. بدل النقل والمواصلات: \${selectedDocEmp.allowances?.transport || 0} ريال سعودي.\\n------------------------------------------------------------\\nإجمالي الدخل المالي الشهري للموظف: (\${totalSalary}) ريال سعودي.\\n\\nوقد أُعطي هذا المشهد والخطاب بناءً على طلبه الشخصي لتقديمه للجهات التي تطلبه، دون أن تتحمل الشركة أو الإدارة أي مسؤولية قانونية أو التزام مالي تجاه الغير.\\n\\nوتقبلوا فائق الاحترام والتقدير،،،\\n\\nقسم شؤون الموظفين والمسيرات المالية\\nشركة فنون الوليد للصناعة\`;
        case 'warning': return \`الرقم المرجعي للإجراء: HR-WRN-\${selectedDocEmp.id}-26\\nتاريخ إصدار الإنذار: \${d}\\n\\nالموضوع: لفت نظر وتوجيه إنذار إداري أولي\\n\\nعناية الموظف الكريم / \${selectedDocEmp['arabicName']} المحترم،\\nبناءً على التوجيهات الإدارية والمتابعة، لوحظ مؤخراً وجود بعض التجاوزات أو التقصير في المهام الموكلة إليكم.\\n\\nنأمل منكم الالتزام بأنظمة ولوائح الشركة لتفادي أي تصعيد إداري في المستقبل.\\n\\nإدارة شؤون الموظفين\`;
        case 'termination': return \`الرقم المرجعي للإجراء: HR-TERM-\${selectedDocEmp.id}-26\\nتاريخ إصدار الإشعار: \${d}\\n\\nالموضوع: إشعار رسمي بإنهاء التعاقد وطي القيد\\n\\nعناية الموظف / \${selectedDocEmp['arabicName']} المحترم،\\nنأسف لإبلاغكم بأنه قد تقرر إنهاء عقد عملكم وتوجيهكم للموارد البشرية لإنهاء إجراءات المخالصة.\\n\\nإدارة شؤون الموظفين\`;
        case 'employee_intro': return \`الرقم المرجعي: INTRO-FAW-\${selectedDocEmp.id}-26\\nالتاريخ: \${d}\\n\\nالموضوع: إفادة رسمية على رأس العمل للجهات المعنية\\n\\nإلى الجهة التي يهمها الأمر المحترمين،\\nنفيدكم بأن الموظف / \${selectedDocEmp['arabicName']} (رقم الإثبات: \${selectedDocEmp.iqamaId}) يعمل لدينا وتحت كفالتنا، وهو على رأس العمل.\\n\\nإدارة شؤون الموظفين\`;
        case 'work_start': return \`الرقم المرجعي: START-FAW-\${selectedDocEmp.id}-26\\nالتاريخ: \${d}\\n\\nالموضوع: إشعار وتوثيق لمباشرة عمل فعلي\\n\\nنفيدكم بأن الموظف / \${selectedDocEmp['arabicName']} قد باشر عمله لدينا بتاريخ \${d}.\\n\\nإدارة الموارد البشرية\`;
        case 'probation_fix': return \`الرقم المرجعي: CONFIRM-FAW-\${selectedDocEmp.id}-26\\nالتاريخ: \${d}\\n\\nالموضوع: إقرار بتجاوز فترة التجربة بنجاح للموظف الجديد\\n\\nعناية الموظف / \${selectedDocEmp['arabicName']} المحترم،\\nنهنئكم باجتياز فترة التجربة بنجاح، ونتمنى لكم مسيرة مهنية موفقة معنا.\\n\\nالمدير التنفيذي\`;
        case 'transfer': return \`الرقم المرجعي: TRANS-FAW-\${selectedDocEmp.id}-26\\nالتاريخ: \${d}\\n\\nالموضوع: إشعار وقرار إداري داخلي بحركة النقل\\n\\nعناية الموظف / \${selectedDocEmp['arabicName']} المحترم،\\nنحيطكم علماً بأنه تقرر نقلكم إلى قسم / إدارة جديدة لتلبية احتياجات العمل.\\n\\nإدارة العمليات\`;
        case 'promotion': return \`الرقم المرجعي: PROM-FAW-\${selectedDocEmp.id}-26\\nالتاريخ: \${d}\\n\\nالموضوع: قرار ترقية ومنح درجة وظيفية مستحقة\\n\\nعناية الموظف / \${selectedDocEmp['arabicName']} المحترم،\\nيسرنا إبلاغكم بترقيتكم إلى مسمى وظيفي جديد بناءً على تقييم أدائكم المتميز.\\n\\nالمدير العام\`;
        case 'leave_request': return \`الرقم المرجعي: LEAVE-FAW-\${selectedDocEmp.id}-26\\nالتاريخ: \${d}\\n\\nالموضوع: مسودة وطلب رسمي لمنح إجازة مجدولة\\n\\nاسم الموظف: \${selectedDocEmp['arabicName']}\\nأتقدم بطلب إجازة تبدأ من تاريخ [.........] وتنتهي في [.........].\\n\\nتوقيع الموظف: ...........................\\nموافقة المدير: ...........................\`;
        case 'contract': return \`الرقم المرجعي المنظم: CONT-FAW-\${selectedDocEmp.id}-26\\nتاريخ الصياغة والتوقيع: \${d}\\n\\nالموضوع: مسودة مشروع عقد عمل موحد\\n\\nالطرف الأول: شركة فنون الوليد للصناعة\\nالطرف الثاني: \${selectedDocEmp['arabicName']}\\n\\nإجمالي الراتب المتفق عليه: \${totalSalary} ريال سعودي.\\n\\nتوقيع الطرف الأول: ....................\\nتوقيع الطرف الثاني: ....................\`;
        case 'custody_receipt': return \`الرقم المرجعي للإيداع والتسليم: CUST-FAW-\${selectedDocEmp.id}-26\\nتاريخ المحضر الموثق: \${d}\\n\\nالموضوع: محضر تسليم عُهد مهنية ومقتنيات\\n\\nأقر أنا الموظف / \${selectedDocEmp['arabicName']} باستلامي للعهد التالية:\\n1. ..............................................................\\n2. ..............................................................\\n\\nتوقيع الموظف الموقر: .......................................\\nمصادقة الإدارة: .......................................\`;
        default: return \`موضوع الإشعار: \${templatesList[docCategory]?.find((t) => t.id === docTemplate)?.name || 'إجراء ونموذج مخصص'}\\nالرقم الأرشيفي المرجعي: DOC-FAW-\${selectedDocEmp.id}-26\\nتاريخ الإصدار: \${d}\\n\\nالبيانات التعريفية للموظف:\\n• الاسم: \${selectedDocEmp['arabicName']}\\n• رقم الإثبات: \${selectedDocEmp.iqamaId}\\n• المسمى الوظيفي: \${selectedDocEmp.jobTitle}\\n\\n------------------------------------------------\\n[اكتب تفاصيل الخطاب هنا]\\n\\n\\n\\n------------------------------------------------\\n\\nتوقيع الموظف: ......................................\\nتوقيع الإدارة: ......................................\`;
      }
    }
  };
`;

const startIndex = code.indexOf('const getTemplateText = () => {');
const endIndex = code.indexOf('};', code.indexOf('default:        // Generic highly formal fallback')) + 2;

if (startIndex !== -1 && endIndex !== -1) {
  code = code.substring(0, startIndex) + replacement.trim() + code.substring(endIndex);
  fs.writeFileSync('src/components/hr/InstantDocumentsHub.tsx', code);
  console.log('Templates updated successfully');
} else {
  console.log('Failed to find template section', startIndex, endIndex);
}
