export const countries = [
  { code: 'sa', ar: 'سعودي', en: 'Saudi Arabia' },
  { code: 'eg', ar: 'مصر', en: 'Egypt' },
  { code: 'ph', ar: 'فلبين', en: 'Philippines' },
  { code: 'in', ar: 'هند', en: 'India' },
  { code: 'pk', ar: 'باكستان', en: 'Pakistan' },
  { code: 'bd', ar: 'بنغلاديش', en: 'Bangladesh' },
  { code: 'ye', ar: 'يمن', en: 'Yemen' },
  { code: 'sy', ar: 'سوريا', en: 'Syria' },
  { code: 'sd', ar: 'سودان', en: 'Sudan' },
  { code: 'jo', ar: 'أردن', en: 'Jordan' },
  { code: 'np', ar: 'نيبال', en: 'Nepal' },
  { code: 'ma', ar: 'مغرب', en: 'Morocco' },
  { code: 'tn', ar: 'تونس', en: 'Tunisia' },
  { code: 'dz', ar: 'جزائر', en: 'Algeria' },
  { code: 'lb', ar: 'لبنان', en: 'Lebanon' },
  { code: 'lk', ar: 'سريلانكا', en: 'Sri Lanka' },
  { code: 'id', ar: 'إندونيسيا', en: 'Indonesia' },
  { code: 'ae', ar: 'إمارات', en: 'United Arab Emirates' },
  { code: 'bh', ar: 'بحرين', en: 'Bahrain' },
  { code: 'kw', ar: 'كويت', en: 'Kuwait' },
  { code: 'om', ar: 'عمان', en: 'Oman' },
  { code: 'qa', ar: 'قطر', en: 'Qatar' },
  { code: 'iq', ar: 'عراق', en: 'Iraq' },
  { code: 'af', ar: 'أفغانستان', en: 'Afghanistan' },
  { code: 'tr', ar: 'تركيا', en: 'Turkey' },
  { code: 'us', ar: 'أمريكا', en: 'United States' },
  { code: 'gb', ar: 'بريطانيا', en: 'United Kingdom' },
  { code: 'cn', ar: 'صين', en: 'China' },
  { code: 'jp', ar: 'يابان', en: 'Japan' },
  { code: 'kr', ar: 'كوريا الجنوبية', en: 'South Korea' },
  { code: 'my', ar: 'ماليزيا', en: 'Malaysia' },
  { code: 'sg', ar: 'سنغافورة', en: 'Singapore' },
  { code: 'th', ar: 'تايلاند', en: 'Thailand' },
  { code: 'vn', ar: 'فيتنام', en: 'Vietnam' },
  { code: 'au', ar: 'أستراليا', en: 'Australia' },
  { code: 'nz', ar: 'نيوزيلندا', en: 'New Zealand' },
  { code: 'ca', ar: 'كندا', en: 'Canada' },
  { code: 'mx', ar: 'المكسيك', en: 'Mexico' },
  { code: 'br', ar: 'البرازيل', en: 'Brazil' },
  { code: 'ar', ar: 'الأرجنتين', en: 'Argentina' },
  { code: 'co', ar: 'كولومبيا', en: 'Colombia' },
  { code: 'cl', ar: 'تشيلي', en: 'Chile' },
  { code: 'pe', ar: 'بيرو', en: 'Peru' },
  { code: 've', ar: 'فنزويلا', en: 'Venezuela' },
  { code: 'za', ar: 'جنوب أفريقيا', en: 'South Africa' },
  { code: 'ng', ar: 'نيجيريا', en: 'Nigeria' },
  { code: 'ke', ar: 'كينيا', en: 'Kenya' },
  { code: 'gh', ar: 'غانا', en: 'Ghana' },
  { code: 'ug', ar: 'أوغندا', en: 'Uganda' },
  { code: 'tz', ar: 'تنزانيا', en: 'Tanzania' },
  { code: 'ru', ar: 'روسيا', en: 'Russia' },
  { code: 'de', ar: 'ألمانيا', en: 'Germany' },
  { code: 'fr', ar: 'فرنسا', en: 'France' },
  { code: 'it', ar: 'إيطاليا', en: 'Italy' },
  { code: 'es', ar: 'إسبانيا', en: 'Spain' },
  { code: 'nl', ar: 'هولندا', en: 'Netherlands' },
  { code: 'be', ar: 'بلجيكا', en: 'Belgium' },
  { code: 'ch', ar: 'سويسرا', en: 'Switzerland' },
  { code: 'se', ar: 'السويد', en: 'Sweden' },
  { code: 'no', ar: 'النرويج', en: 'Norway' },
  { code: 'fi', ar: 'فنلندا', en: 'Finland' },
  { code: 'dk', ar: 'الدنمارك', en: 'Denmark' },
  { code: 'pl', ar: 'بولندا', en: 'Poland' },
  { code: 'ua', ar: 'أوكرانيا', en: 'Ukraine' },
  { code: 'ro', ar: 'رومانيا', en: 'Romania' },
  { code: 'cz', ar: 'التشيك', en: 'Czech Republic' },
  { code: 'gr', ar: 'اليونان', en: 'Greece' },
  { code: 'pt', ar: 'البرتغال', en: 'Portugal' },
  { code: 'hu', ar: 'المجر', en: 'Hungary' },
  { code: 'at', ar: 'النمسا', en: 'Austria' },
  { code: 'ir', ar: 'إيران', en: 'Iran' },
  { code: 'mm', ar: 'ميانمار', en: 'Myanmar' },
  { code: 'uz', ar: 'أوزبكستان', en: 'Uzbekistan' },
  { code: 'kz', ar: 'كازاخستان', en: 'Kazakhstan' },
  { code: 'tj', ar: 'طاجيكستان', en: 'Tajikistan' },
  { code: 'kg', ar: 'قيرغيزستان', en: 'Kyrgyzstan' },
  { code: 'tm', ar: 'تركمانستان', en: 'Turkmenistan' },
  { code: 'az', ar: 'أذربيجان', en: 'Azerbaijan' },
  { code: 'ge', ar: 'جورجيا', en: 'Georgia' },
  { code: 'am', ar: 'أرمينيا', en: 'Armenia' },
  { code: 'mv', ar: 'المالديف', en: 'Maldives' },
  { code: 'bt', ar: 'بوتان', en: 'Bhutan' },
  { code: 'by', ar: 'بيلاروسيا', en: 'Belarus' },
  { code: 'rs', ar: 'صربيا', en: 'Serbia' },
  { code: 'bg', ar: 'بلغاريا', en: 'Bulgaria' },
  { code: 'sk', ar: 'سلوفاكيا', en: 'Slovakia' },
  { code: 'hr', ar: 'كرواتيا', en: 'Croatia' },
  { code: 'ba', ar: 'البوسنة والهرسك', en: 'Bosnia and Herzegovina' },
  { code: 'al', ar: 'ألبانيا', en: 'Albania' },
  { code: 'mk', ar: 'مقدونيا الشمالية', en: 'North Macedonia' },
  { code: 'si', ar: 'سلوفينيا', en: 'Slovenia' },
  { code: 'lv', ar: 'لاتفيا', en: 'Latvia' },
  { code: 'ee', ar: 'إستونيا', en: 'Estonia' },
  { code: 'lt', ar: 'ليتوانيا', en: 'Lithuania' },
  { code: 'cy', ar: 'قبرص', en: 'Cyprus' },
  { code: 'mt', ar: 'مالطا', en: 'Malta' },
  { code: 'is', ar: 'آيسلندا', en: 'Iceland' },
  { code: 'ie', ar: 'أيرلندا', en: 'Ireland' },
  { code: 'il', ar: 'فلسطين المحتلة (إسرائيل)', en: 'Israel' },
  { code: 'ps', ar: 'فلسطين', en: 'Palestine' },
  { code: 'ly', ar: 'ليبيا', en: 'Libya' },
  { code: 'mr', ar: 'موريتانيا', en: 'Mauritania' },
  { code: 'so', ar: 'الصومال', en: 'Somalia' },
  { code: 'dj', ar: 'جيبوتي', en: 'Djibouti' },
  { code: 'km', ar: 'جزر القمر', en: 'Comoros' },
  { code: 'er', ar: 'إريتريا', en: 'Eritrea' },
  { code: 'et', ar: 'إثيوبيا', en: 'Ethiopia' },
  { code: 'ss', ar: 'جنوب السودان', en: 'South Sudan' },
  { code: 'cm', ar: 'الكاميرون', en: 'Cameroon' },
  { code: 'ci', ar: 'ساحل العاج', en: 'Ivory Coast' },
  { code: 'sn', ar: 'السنغال', en: 'Senegal' },
  { code: 'ml', ar: 'مالي', en: 'Mali' },
  { code: 'bf', ar: 'بوركينا فاسو', en: 'Burkina Faso' },
  { code: 'ne', ar: 'النيجر', en: 'Niger' },
  { code: 'td', ar: 'تشاد', en: 'Chad' },
  { code: 'cf', ar: 'جمهورية أفريقيا الوسطى', en: 'Central African Republic' },
  { code: 'cd', ar: 'الكونغو الديمقراطية', en: 'Democratic Republic of the Congo' },
  { code: 'cg', ar: 'الكونغو', en: 'Republic of the Congo' },
  { code: 'ga', ar: 'الغابون', en: 'Gabon' },
  { code: 'gq', ar: 'غينيا الاستوائية', en: 'Equatorial Guinea' },
  { code: 'ao', ar: 'أنغولا', en: 'Angola' },
  { code: 'mz', ar: 'موزمبيق', en: 'Mozambique' },
  { code: 'zm', ar: 'زامبيا', en: 'Zambia' },
  { code: 'zw', ar: 'زيمبابوي', en: 'Zimbabwe' },
  { code: 'mw', ar: 'مالاوي', en: 'Malawi' },
  { code: 'mg', ar: 'مدغشقر', en: 'Madagascar' },
  { code: 'mu', ar: 'موريشيوس', en: 'Mauritius' },
  { code: 'rw', ar: 'رواندا', en: 'Rwanda' },
  { code: 'bi', ar: 'بوروندي', en: 'Burundi' },
  { code: 'tg', ar: 'توجو', en: 'Togo' },
  { code: 'bj', ar: 'بنين', en: 'Benin' },
  { code: 'lr', ar: 'ليبيريا', en: 'Liberia' },
  { code: 'sl', ar: 'سيراليون', en: 'Sierra Leone' },
  { code: 'gn', ar: 'غينيا', en: 'Guinea' },
  { code: 'gw', ar: 'غينيا بيساو', en: 'Guinea-Bissau' },
  { code: 'gm', ar: 'غامبيا', en: 'Gambia' },
  { code: 'cv', ar: 'الرأس الأخضر', en: 'Cape Verde' },
  { code: 'st', ar: 'ساو تومي وبرينسيب', en: 'Sao Tome and Principe' },
];

export const getNationalityCode = (nationality: string | undefined): string => {
  if (!nationality) return 'sa';
  const lowered = nationality.trim().toLowerCase();
  
  // Direct match
  const found = countries.find(c => lowered === c.ar.toLowerCase() || lowered === c.en.toLowerCase());
  if (found) return found.code;

  // Substring match
  const subMatch = countries.find(c => lowered.includes(c.ar.toLowerCase()) || c.ar.toLowerCase().includes(lowered));
  if (subMatch) return subMatch.code;

  return 'un';
};
