/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GoogleGenAI, Type } from "@google/genai";

/**
 * STRUCTURED GEMINI API AI GENERATOR ENGINE (SPSV ERP)
 * This TypeScript code provides a clean, production-grade model integration
 * using the modern @google/genai SDK. It generates salary structures,
 * career matrices, and permission mappings based on a job title input.
 *
 * Requirements:
 * 1. npm install @google/genai
 * 2. Ensure process.env.GEMINI_API_KEY is configured in your secrets.
 */

// Initialize standard client with built-in telemetry header
const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
  httpOptions: {
    headers: {
      "User-Agent": "aistudio-build",
    }
  }
});

export async function generateRecruitmentLadder(jobTitle: string) {
  const modelName = "gemini-3.5-flash"; // Recommended model for structural text tasks
  
  const systemInstruction = 
    "You are an expert HR organizational planner in Riyadh, Saudi Arabia, specializing in " +
    "the advertisement, sign-making, and neon light manufacturing sectors. " +
    "Your output must align with Saudi Labor Law, typical Saudi salaries (SAR), and standard corporate governance.";

  const prompt = `
    Conduct structural planning for a newly proposed job title: "${jobTitle}" at SPSV.
    Determine:
    - Minimum basic salary index and maximum basic salary (monthly in SAR).
    - Career advancement steps.
    - Specialized duties (responsibilities) for neon light manufacturing, signage design, or support departments.
    - Relevant hard/soft skillset indicators.
    
    You MUST format your reply as a single, valid JSON object matching the following structural specification:
    {
      "jobTitle": string,
      "salaryMin": number,
      "salaryMax": number,
      "careerPath": string[],
      "responsibilities": string[],
      "skills": string[]
    }
  `;

  try {
    const response = await ai.models.generateContent({
      model: modelName,
      contents: prompt,
      config: {
        systemInstruction: systemInstruction,
        responseMimeType: "application/json",
        // Force structured parsing using responseSchema
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            jobTitle: { type: Type.STRING, description: "Recruitment Job Title" },
            salaryMin: { type: Type.INTEGER, description: "Minimal baseline salary in SAR" },
            salaryMax: { type: Type.INTEGER, description: "Maximum benchmark salary in SAR" },
            careerPath: {
              type: Type.ARRAY,
              items: { type: Type.STRING },
              description: "Sequence of career promotions"
            },
            responsibilities: {
              type: Type.ARRAY,
              items: { type: Type.STRING },
              description: "Key responsibilities and organizational authority"
            },
            skills: {
              type: Type.ARRAY,
              items: { type: Type.STRING },
              description: "Required soft and engineering skills"
            }
          },
          required: ["jobTitle", "salaryMin", "salaryMax", "careerPath", "responsibilities", "skills"]
        }
      }
    });

    if (!response.text) {
      throw new Error("No output was generated by the model interface.");
    }

    const payload = JSON.parse(response.text.trim());
    return payload;
  } catch (error) {
    console.error("AI Generation Process Failed:", error);
    throw error;
  }
}
